services:
  backend:
    image: storynode
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: package.json
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 3000:3000