services:
  backend:
    image: storynode
    build:
      context: ./backend
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: package.json
    volumes:
      - ./backend/src:/app/src
      - ./backend/openapi.yaml:/app/openapi.yaml
    ports:
      - 3000:3000